### ISSUE TITLE
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

### ISSUE THREAD

**Issue by Integratedhaplotypescore** [cran/detectRUNS#1]
Dear @filippob 

When I run the tableRuns() command in detectRUNS, I get the following error. Can you help me solve this error?

topRuns <- tableRuns(runs =  slidingRuns,  genotypeFile = "ESMEclean.no-tabs.ped", mapFile = "False_clean.map", threshold = 0.5)

Threshold used: 50
I found only Runs data frame. GOOD!
Calculation % SNP in ROH
Chromosome founds:  26
  |===============================================================================| 100%
Calculation % SNP in ROH finish
checking:  ESME
Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Integratedhaplotypescore** [comment]
Hi @gaborcsardi 

Sorry. I think I did something wrong. Do I need to remove this issue? I couldn't find a way to delete the issue.

**Comment by gaborcsardi** [comment]
No worries at all, no need to remove the issue. You can even direct the authors here if they don't have an issue tracker and you want to. Otherwise just close it and that's it.
